# Generated by Django 4.2.3 on 2023-08-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0002_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='none', max_length=50, null=True),
        ),
    ]
