# Generated by Django 4.2.3 on 2023-08-24 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0003_movie_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_time', models.DateTimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slot_movies', to='filmapp.movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='time_slots',
            field=models.ManyToManyField(related_name='movie_time_slots', to='filmapp.timeslot'),
        ),
    ]
