# Generated by Django 4.2.3 on 2023-08-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0004_timeslot_movie_time_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='time_slots',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
