# Generated by Django 4.2.3 on 2023-07-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('licence', models.FileField(blank=True, max_length=50, null=True, upload_to='theater_licences/')),
                ('contact_number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='theater_photos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
