# Generated by Django 4.2.3 on 2023-08-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theaterapp', '0002_theater_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
