# Generated by Django 4.2.3 on 2023-08-23 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0003_movie_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Theaterapp', '0005_theater_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('seat_number', models.IntegerField()),
                ('is_booked', models.BooleanField(default=False)),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Theaterapp.theater')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmapp.movie')),
                ('seats_booked', models.ManyToManyField(related_name='bookings', to='Theaterapp.seat')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Theaterapp.theater')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
