# Generated by Django 4.2.3 on 2023-08-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Theaterapp', '0007_timeslot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
