# Generated by Django 4.2.3 on 2023-08-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0005_remove_movie_time_slots_delete_timeslot'),
        ('Theaterapp', '0009_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='movies',
            field=models.ManyToManyField(null=True, related_name='theaters', to='filmapp.movie'),
        ),
    ]
