# Generated by Django 4.2.3 on 2023-09-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0005_remove_movie_time_slots_delete_timeslot'),
        ('Theaterapp', '0011_alter_theater_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='theater',
        ),
        migrations.AlterField(
            model_name='theater',
            name='movies',
            field=models.ManyToManyField(related_name='theaters', to='filmapp.movie'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
