# Generated by Django 4.2.3 on 2023-09-06 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filmapp', '0005_remove_movie_time_slots_delete_timeslot'),
        ('Theaterapp', '0012_remove_seat_theater_alter_theater_movies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('row_number', models.IntegerField()),
                ('seat_number', models.IntegerField()),
                ('is_booked', models.BooleanField(default=False)),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Theaterapp.theater')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmapp.movie')),
                ('seats_booked', models.ManyToManyField(related_name='bookings', to='Theaterapp.seat')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Theaterapp.theater')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
