# Generated by Django 4.2.3 on 2023-09-06 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Theaterapp', '0013_seat_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
