# Generated by Django 4.2.3 on 2023-09-06 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Theaterapp', '0015_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
