# Generated by Django 4.2.3 on 2023-09-07 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Theaterapp', '0017_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_id', models.CharField(max_length=100, unique=True)),
                ('method', models.CharField(choices=[('credit_card', 'Credit Card'), ('razorpay', 'RazorPay'), ('bank_transfer', 'Bank Transfer')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bookings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Theaterapp.booking')),
            ],
        ),
    ]
