# Generated by Django 4.2.3 on 2023-09-07 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Theaterapp', '0018_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
    ]
