# Generated by Django 4.2.3 on 2023-09-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theaterapp', '0019_remove_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
