# Generated by Django 4.2.3 on 2023-09-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theaterapp', '0023_remove_timeslot_slot_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
