# Generated by Django 4.2.3 on 2023-09-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theaterapp', '0024_theater_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Booked', max_length=20),
        ),
    ]
