# Generated by Django 4.2.3 on 2023-09-12 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_user_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_blocked',
        ),
    ]
